library(dplyr)
library(stringr)
library(BHH2)

my_data                                         <- read.csv("DSProj.csv",na.strings = c("", "NA"),stringsAsFactors=FALSE)
colnames(my_data)                               <- c("ID", "Animal_Type","Park","Abundance","Latitude","Longitude","Acreage")
#This creates new variables that are named based off which animal category they are in. It also helps change the abundance category into a number which helps quantify the data.
my_data$Abundance[my_data$Abundance=="Unknown"] <- NA
DSProj           <- na.omit(my_data)
DSProj$Animal_Type <- str_replace_all(DSProj$Animal_Type, "/", "_")
DSProj$Abundance[DSProj$Abundance=="Abundant"]<-5
DSProj$Abundance[DSProj$Abundance=="Common"]<-4
DSProj$Abundance[DSProj$Abundance=="Occasional"]<-3
DSProj$Abundance[DSProj$Abundance=="Uncommon"]<-2
DSProj$Abundance[DSProj$Abundance=="Rare"]<-1
DSProj$Abundance <- as.numeric(DSProj$Abundance)
DSProj_mammal<-filter(DSProj,Animal_Type=="Mammal")
DSProj_fish<-filter(DSProj,Animal_Type=="Fish")
DSProj_vascular_plant<-filter(DSProj,Animal_Type=="Vascular Plant")
DSProj_bird<-filter(DSProj,Animal_Type=="Bird")
DSProj_insect<-filter(DSProj,Animal_Type=="Insect")
DSProj_nonvascular_plant<-filter(DSProj,Animal_Type=="Nonvascular Plant")
DSProj_reptile<-filter(DSProj,Animal_Type=="Reptile")
DSProj_amphibian<-filter(DSProj,Animal_Type=="Amphibian")
DSProj_fungi<-filter(DSProj,Animal_Type=="Fungi")
DSProj_algae<-filter(DSProj,Animal_Type=="Algae")
DSProj_crab_lobster_shrimp<-filter(DSProj,Animal_Type== "Crab_Lobster_Shrimp")
DSProj_invertebrate<-filter(DSProj,Animal_Type=="Invertebrate")
DSProj_slug_snail<-filter(DSProj,Animal_Type=="Slug_Snail")
DSProj_spider_scorpion<-filter(DSProj,Animal_Type=="Spider_Scorpion")
lm.fit <- lm(Abundance~Latitude+Longitude+Acreage,data=DSProj_mammal)
print(summary(lm.fit))

lm.fit <- lm(Abundance~Latitude+Longitude+Acreage,data=DSProj_fish)
print(summary(lm.fit))
lm.fit <-lm(Abundance~Latitude+Longitude+Acreage,data=DSProj_vascular_plant)
print(summary(lm.fit))
lm.fit <-lm(Abundance~Latitude+Longitude+Acreage,data=DSProj_bird)
print(summary(lm.fit))
lm.fit <-lm(Abundance~Latitude+Longitude+Acreage,data=DSProj_insect)
print(summary(lm.fit))
lm.fit <-lm(Abundance~Latitude+Longitude+Acreage,data=DSProj_nonvascular_plant)
print(summary(lm.fit))
lm.fit <-lm(Abundance~Latitude+Longitude+Acreage,data=DSProj_reptile)
print(summary(lm.fit))
lm.fit <-lm(Abundance~Latitude+Longitude+Acreage,data=DSProj_amphibian)
print(summary(lm.fit))
lm.fit <-lm(Abundance~Latitude+Longitude+Acreage,data=DSProj_fungi)
print(summary(lm.fit))
lm.fit <-lm(Abundance~Latitude+Longitude+Acreage,data=DSProj_algae)
print(summary(lm.fit))
lm.fit<-lm(Abundance~Latitude+Longitude+Acreage,data=DSProj_crab_lobster_shrimp)
print(summary(lm.fit))
lm.fit <-lm(Abundance~Latitude+Longitude+Acreage,data=DSProj_invertebrate)
print(summary(lm.fit))
lm.fit <-lm(Abundance~Latitude+Longitude+Acreage,data=DSProj_slug_snail)
print(summary(lm.fit))
lm.fit <-lm(Abundance~Latitude+Longitude+Acreage,data=DSProj_spider_scorpion)
print(summary(lm.fit))
#This code does the linear regression and visualize it as well
lm.fit <- lm(Abundance~Latitude+Longitude+Acreage,data=DSProj_mammal)
print(summary(lm.fit))
#From this line until the end the code helps create a plot with a line of best fit showing the linear regresssion of the data while also giving a summary including mean, median, mode, sd, etc.
with(DSProj_mammal,plot(Latitude,Abundance))
with(DSProj_mammal,abline(lm(Abundance~Latitude)))
summary(with(DSProj_mammal,lm(Abundance~Latitude)))
lm.fit <- lm(Abundance~Latitude+Longitude+Acreage,data=DSProj_fish)
print(summary(lm.fit))
with(DSProj_fish,plot(Latitude,Abundance))
with(DSProj_fish,abline(lm(Abundance~Latitude)))
summary(with(DSProj_fish,lm(Abundance~Latitude)))
lm.fit<-lm(Abundance~Latitude+Longitude+Acreage,data=DSProj_vascular_plant)
print(summary(lm.fit))
with(DSProj_vascular_plant,plot(Latitude,Abundance))
with(DSProj_vascular_plant,abline(lm(Abundance~Latitude)))
summary(with(DSProj_vascular_plant,lm(Abundance~Latitude)))
lm.fit <-lm(Abundance~Latitude+Longitude+Acreage,data=DSProj_bird)
print(summary(lm.fit))
with(DSProj_bird,plot(Latitude,Abundance))
with(DSProj_bird,abline(lm(Abundance~Latitude)))
summary(with(DSProj_bird,lm(Abundance~Latitude)))
lm.fit<-lm(Abundance~Latitude+Longitude+Acreage,data=DSProj_insect)
print(summary(lm.fit))
with(DSProj_insect,plot(Latitude,Abundance))
with(DSProj_insect,abline(lm(Abundance~Latitude)))
summary(with(DSProj_insect,lm(Abundance~Latitude)))
lm.fit<-lm(Abundance~Latitude+Longitude+Acreage,data=DSProj)
print(summary(lm.fit))
with(DSProj_nonvascular_plant,plot(Latitude,Abundance))
with(DSProj_nonvascular_plant,abline(lm(Abundance~Latitude)))
summary(with(DSProj_nonvascular_plant,lm(Abundance~Latitude)))
lm.fit<-lm(Abundance~Latitude+Longitude+Acreage,data=DSProj_reptile)
print(summary(lm.fit))
with(DSProj_reptile,plot(Latitude,Abundance))
with(DSProj_reptile,abline(lm(Abundance~Latitude)))
summary(with(DSProj_reptile,lm(Abundance~Latitude)))
lm.fit<-lm(Abundance~Latitude+Longitude+Acreage,data=DSProj_amphibian)
print(summary(lm.fit))
with(DSProj_amphibian,plot(Latitude,Abundance))
with(DSProj_amphibian,abline(lm(Abundance~Latitude)))
summary(with(DSProj_amphibian,lm(Abundance~Latitude)))
lm.fit<-lm(Abundance~Latitude+Longitude+Acreage,data=DSProj_fungi)
print(summary(lm.fit))
with(DSProj_fungi,plot(Latitude,Abundance))
with(DSProj_fungi,abline(lm(Abundance~Latitude)))
summary(with(DSProj_fungi,lm(Abundance~Latitude)))
lm.fit<-lm(Abundance~Latitude+Longitude+Acreage,data=DSProj_algae)
print(summary(lm.fit))
with(DSProj_algae,plot(Latitude,Abundance))
with(DSProj_algae,abline(lm(Abundance~Latitude)))
summary(with(DSProj_algae,lm(Abundance~Latitude)))
lm.fit<-lm(Abundance~Latitude+Longitude+Acreage,data=DSProj_crab_lobster_shrimp)
print(summary(lm.fit))
with(DSProj_crab_lobster_shrimp,plot(Latitude,Abundance))
with(DSProj_crab_lobster_shrimp,abline(lm(Abundance~Latitude)))
summary(with(DSProj_crab_lobster_shrimp,lm(Abundance~Latitude)))
lm.fit<-lm(Abundance~Latitude+Longitude+Acreage,data=DSProj_invertebrate)
print(summary(lm.fit))
with(DSProj_invertebrate,plot(Latitude,Abundance))
with(DSProj_invertebrate,abline(lm(Abundance~Latitude)))
summary(with(DSProj_invertebrate,lm(Abundance~Latitude)))
lm.fit<-lm(Abundance~Latitude+Longitude+Acreage,data=DSProj_slug_snail)
print(summary(lm.fit))
with(DSProj_slug_snail,plot(Latitude,Abundance))
with(DSProj_slug_snail,abline(lm(Abundance~Latitude)))
summary(with(DSProj_slug_snail,lm(Abundance~Latitude)))
lm.fit<-lm(Abundance~Latitude+Longitude+Acreage,data=DSProj_spider_scorpion)
print(summary(lm.fit))
with(DSProj_spider_scorpion,plot(Latitude,Abundance))
with(DSProj_spider_scorpion,abline(lm(Abundance~Latitude)))
summary(with(DSProj_spider_scorpion,lm(Abundance~Latitude)))


